### ISSUE TITLE
Unhelpful jing error message when using an invalid element

### ISSUE THREAD

**Issue by ghost** [openSUSE/daps#370]
I just had the issue that I validated a document that had this construct:

```
<sect>
[...snip a hundred lines...]
<sect1>
```

`sect` is of course not allowed at all but `sect1` is.
It is somehow important to use the `sect1` element to demonstrate this -- for example, `info` gives a much better error message.

The error message I got was this:

`file.xml:101: parser error : expected '>'  </sect1>        ^.  Stop.`

Which is really unhelpful: It points you at the closing tag, not the start tag, and it does not make sense.

I checked with toms and he got a better error message including the information that `sect` is not allowed (on 42.1).

At first I thought it had to with the script I use to run `daps validate` filtering away messages that are on stdout but that is not the issue, it seems. I could reproduce in a normal command line `daps validate` run (on 13.2) and cwickert could reproduce it too (on 42.1).

So, now I wonder if maybe something is different on toms's side ... theories:
1. He has some RPMs installed that I lack.
2. His Oxygen version ships with a better jing that is somehow called instead of the system jing (?).
3. There is some environment variable/dapsrc setting that controls this behavior, and it is set to the wrong value on my system.

Ftr, I could reproduce this with `-vv` and `--debug` options, I tried `daps clean` etc.

**Comment by fsundermeyer** [comment]
I cannot reproduce this error - maybe it has been fixed in between (bug report is rather old). With both, Tumbleweed and 42.3 I get the same error messages:

```
> daps -d DC-SLES-admin validate                                                                                                     [master|●1⚑1]
/local/git/doc-sle/xml/vnc.xml:117: parser error : Opening and ending tag mismatch: sect1 line 37 and sect
 </sect>
        ^
/local/git/doc-sle/xml/vnc.xml:117: parser error : Opening and ending tag mismatch: sect1 line 37 and sect
 </sect>
        ^
unable to parse /local/git/doc-sle/xml/vnc.xml
make: *** [/usr/share/daps/make/profiling.mk:117: /local/git/doc-sle/build/.profiled/x86_64_zseries_power_aarch64_sles/vnc.xml] Error 6
```

**Comment by ghost** [comment]
You are doing it the other way round:

My example was: `<sect>...</sect1>`

You used: `<sect1> ... </sect>`

I can still reproduce.

**Comment by fsundermeyer** [comment]
This is no DAPS bug, but a jing "issue".

jing-20091111-26.1 on 42.3 shows the behavior you describe.
jing-20151127-4.5 on Tumbleweed shows the error message you expect.

**Comment by fsundermeyer** [comment]
Closing -- this is nothing that can be fixed in DAPS
